version: '3.8'

services:
  postgres:
    image: postgres:15  # Use the latest stable version of PostgreSQL
    container_name: postgres-container
    environment:
      POSTGRES_DB: universitydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"  # Expose PostgreSQL port to host
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data between restarts

  university-api-app:
    image: university-api
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/universitydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: example
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data:
